[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#911227"
backgroundColor = "#000000"
secondaryBackgroundColor = "#2a2121"
textColor = "#f5f5f5"
font = "sans serif"

[browser]
gatherUsageStats = false
